# MC2FA v${project.version} Configuration

# Whether or not MC2FA should report back stats to MCStats.xyz
MCStats: true

# Whether 2FA should be forced, supports true, false or OP
Forced: false

# Disable all commands if not yet authenticated (other than 2fa ones)
Disable Commands: true

# If the above is true you can whitelist commands with the below
Whitelisted Commands:
  - "help"

# If commands are not disabled you can use the below to blacklist specific commands instead
Blacklisted Commands:
  - "op"
  - "spawn"

# Advise of 2FA - Whether to send a message to players on join notifying them that 2FA is available.
Advise: true

# Use GUI keypad - Whether or not to show the keypad for users to enter their key on join
GUI Keypad: true

# OTP label - Label that is shown in the two-factor application
OTP Label: "%%name%%:MC2FA"

# Key storage, either FLAT, SQLite or MYSQL - SQLite and MySQL are not yet supported and are planned for the future
Key Storage: FLAT