# MC2FA v${project.version} Configuration

# Whether or not MC2FA should report back stats to MCStats.xyz
MCStats: true

# Whether 2FA should be forced, supports true, false or OP
Forced: false

# Disable all commands if not yet authenticated (other than 2fa ones)
Disable Commands: true

# If the above is true you can whitelist commands with the below
Whitelisted Commands:
  - "help"

# If commands are not disabled you can use the below to blacklist specific commands instead
Blacklisted Commands:
  - "op"
  - "spawn"

# Key storage, either FLAT or MYSQL - MySQL is not yet supported
Key Storage: FLAT

# If the above is MYSQL please enter MySQL connection details (Coming Soon)
MySQL Host: 127.0.0.1
MySQL Port: 3306
MySQL User: username
MySQL Pass: password
MySQL Database: database